/* This file is autogenerated from the 'typesconfig' program
 * in the sal module
 */

#define SAL_TYPES_ALIGNMENT2	1
#define SAL_TYPES_ALIGNMENT4	1
#define SAL_TYPES_ALIGNMENT8	1
#define SAL_TYPES_SIZEOFSHORT	2
#define SAL_TYPES_SIZEOFINT	4
#define SAL_TYPES_SIZEOFLONG	8
#define SAL_TYPES_SIZEOFLONGLONG	8
#define SAL_TYPES_SIZEOFPOINTER	8
