# $Header: //MyDataDepot/Projects/provenance-autoType2/haathi/tesseract/makefile#1 $
#DIR = ../../libcpp/leptonica/Linux
#SUBDIR = leptonica-1.68
#
#$(DIR)/$(SUBDIR)/configure: $(DIR)/leptonica-1.68.tar.gz
#	cd $(DIR) && tar -xvzf leptonica-1.68.tar.gz
#	touch $(DIR)/$(SUBDIR)/configure
#
#/usr/local/lib/liblept.a: $(DIR)/$(SUBDIR)/configure
#	cd $(DIR)/$(SUBDIR) && ./configure
#	cd $(DIR)/$(SUBDIR) && make
#	@echo "******************************************************"
#	@echo "You will need to run"
#	@echo "cd $(DIR) && sudo make install"
#	@echo "from the command line to complete installation."
#	@echo "******************************************************"
#
#all: /usr/local/lib/liblept.a
#
#clean:
#	cd $(DIR)/$(SUBDIR) && make clean
#	rm -rf $(DIR)/$(SUBDIR)

all:
	@echo "Nothing to build"
	
clean:
	@echo "Nothing to clean"
	

